export const API = {
    auth: {
        login: '/api/auth/login',
        register: '/api/auth/register',
        refresh: '/api/auth/refresh',
        revoke: '/api/auth/revoke',
        logout: '/api/auth/logout',
        profile: '/api/auth/profile',
        forgotPassword: '/api/auth/forgot-password',
        resetPassword: '/api/auth/reset-password',
    },
    patients: {
        base: '/api/patient',
        byId: (id: string) => `/api/patient/${id}`,
        archive: (id: string) => `/api/patient/${id}/archive`,
        restore: (id: string) => `/api/patient/${id}/restore`,
        intake: (id: string) => `/api/patient/${id}/intake`,
        assessments: (id: string) => `/api/patient/${id}/assessments`,
    },
    sessions: {
        base: '/api/sessions',
        byPatient: (patientId: string) => `/api/sessions/patient/${patientId}`,
        byId: (id: string) => `/api/sessions/${id}`,
        summary: (id: string) => `/api/sessions/${id}/summary`,
    },
    exercises: {
        base: '/api/exercises',
        byPatient: (patientId: string) => `/api/exercises/patient/${patientId}`,
        myExercises: '/api/exercises/my',
        log: '/api/exercises/log',
        myLogs: '/api/exercises/my/logs',
    },
    reports: {
        base: '/api/reports',
        generate: '/api/reports/generate',
        byId: (id: string) => `/api/reports/${id}`,
        approve: (id: string) => `/api/reports/${id}/approve`,
        reject: (id: string) => `/api/reports/${id}/reject`,
        export: (id: string) => `/api/reports/${id}/export`,
    },
    dashboard: {
        summary: '/api/progress/dashboard',
    },
    notifications: {
        base: '/api/notifications',
        markRead: (id: string) => `/api/notifications/${id}/read`,
        markAllRead: '/api/notifications/read-all',
    },
    chat: {
        conversations: '/api/chat/conversations',
        conversation: (conversationId: string) => `/api/chat/conversations/${conversationId}`,
        conversationsByPatient: (patientId: string) => `/api/chat/conversations?patientId=${patientId}`,
        history: (conversationId: string) => `/api/chat/${conversationId}/history`,
        send: '/api/chat/send',
        close: (conversationId: string) => `/api/chat/conversations/${conversationId}/close`,
    },
} as const;
