export const API = {
    auth: {
        login: '/api/auth/login',
        register: '/api/auth/register',
        refresh: '/api/auth/refresh',
        revoke: '/api/auth/revoke',
        logout: '/api/auth/logout',
        profile: '/api/auth/profile',
        forgotPassword: '/api/auth/forgot-password',
        resetPassword: '/api/auth/reset-password',
    },
    patients: {
        base: '/api/patient',
        byId: (id: string) => `/api/patient/${id}`,
        archive: (id: string) => `/api/patient/${id}/archive`,
        restore: (id: string) => `/api/patient/${id}/restore`,
        intake: (id: string) => `/api/patient/${id}/intake`,
        intakeImage: (id: string) => `/api/patient/${id}/intake/image`,
        assessments: (id: string) => `/api/patient/${id}/assessments`,
    },
    sessions: {
        base: '/sessions',
        byPatient: (patientId: string) => `/sessions/patient/${patientId}`,
        byId: (id: string) => `/sessions/${id}`,
        voice: (id: string) => `/sessions/${id}/voice`,
        summary: (id: string) => `/sessions/${id}/summary`,
    },
    exercises: {
        base: '/exercises',
        assign: '/exercises/assign',
        byPatient: (patientId: string) => `/exercises/patient/${patientId}`,
        status: (id: string) => `/exercises/${id}/status`,
    },
    reports: {
        base: '/reports',
        generate: '/reports/generate',
        byId: (id: string) => `/reports/${id}`,
        approve: (id: string) => `/reports/${id}/approve`,
        reject: (id: string) => `/reports/${id}/reject`,
        export: (id: string) => `/reports/${id}/export`,
    },
    dashboard: {
        stats: '/dashboard/stats',
        trends: '/dashboard/trends',
    },
    chat: {
        history: (sessionId: string) => `/chat/${sessionId}/history`,
        send: '/chat/send',
    },
} as const;
